### ISSUE TITLE
Merge dynannotate-improvements branch to master branch

### ISSUE THREAD

**Issue by oflg** [TWPUB/TWPUB-Tools#15]
Any plans to merge the [dynannotate-improvements](https://github.com/Jermolene/TiddlyWiki5/tree/dynannotate-improvements) branch into the main branch? 

This could support excerpts of non-textual content such as images.

**Comment by Jermolene** [comment]
Hi @oflg yes! The hold up is that it depends on the new JSON filter operators (see https://github.com/Jermolene/TiddlyWiki5/pull/6522) which is now almost ready to merge (just some more docs updates).
